openapi: 3.0.1
info:
  title: Ensembl - 2020
  description: API for 2020.ensembl.org
  contact:
    email: kamal@ebi.ac.uk
  version: 0.0.1
servers:
- url: https://2020.ensembl.org
- url: http://2020.ensembl.org
tags:
- name: api
  description: Genome searcch
paths:
  /api/genome/info/:
    get:
      tags:
      - api
      summary: Returns information about particular genome
      description: Returns a single genome
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  genome_info:
                    type: array
                    items:
                      $ref: '#/components/schemas/Genome'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome not found
          content: {}
      security:
      - api_key: []
  /api/popular_genomes/:
    get:
      tags:
      - api
      summary: Get popular genomes
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  popular_species:
                    type: array
                    items:
                      $ref: '#/components/schemas/Genome'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome not found
          content: {}
      security:
      - api_key: []
  /api/alternative_assemblies/:
    get:
      tags:
      - api
      summary: Get alternative assemblies for given genome
      description: ""
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  alternate_assemblies:
                    type: array
                    items:
                      $ref: '#/components/schemas/Assembly'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Alternate assemblies not found
          content: {}
      security:
      - api_key: []
  /api/genome/track_categories/:
    get:
      tags:
      - api
      summary: Get track ctegories for given genome
      description: Returns track categories for given genome
      parameters:
      - name: genome_id
        in: query
        description: genome_id for which track categories are requested
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  track_categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/TrackCategory'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome ID not found
          content: {}
      security:
      - api_key: [] 
  /api/object/info/:
    get:
      tags:
      - api
      summary: Get object info for given object_id
      description: Returns info for given object
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      - name: object_id
        in: query
        description: object_id
        required: true
        schema:
          type: string
          default: gene:ENSG00000139618
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
              examples:
                object-info-gene-success:
                  $ref: '#/components/examples/object-info-gene-response'
                object-info-region-success:
                  $ref: '#/components/examples/object-info-region-response'
        400:
          description: Invalid Genome ID
          content: 
            application/json:
              examples:
                missing-genome_id-param:
                  $ref: '#/components/examples/missing-genome_id-param-response'
                missing-genome_id-value:
                  $ref: '#/components/examples/missing-genome_id-value-response'
                invalid-genome_id:
                  $ref: '#/components/examples/invalid-genome_id-response'
        404:
          description: Genome ID not found
          content: {}
      security:
      - api_key: []
  /api/object/track_list:
    get:
      tags:
      - api
      summary: Get list of track for given object and genome_id
      description: Returns info for given object
      parameters:
      - name: genome_id
        in: query
        description: genome id of the object
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      - name: object_id
        in: query
        description: object_id
        required: true
        schema:
          type: string
          default: gene:ENSG00000139618
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackList'
              examples:
                track-list-gene-success:
                  $ref: '#/components/examples/track-list-gene-response'
        400:
          description: Invalid Genome ID
          content:
            application/json:
              examples:
                missing-genome_id-param:
                  $ref: '#/components/examples/missing-genome_id-param-response'
                missing-genome_id-value:
                  $ref: '#/components/examples/missing-genome_id-value-response'
                invalid-genome_id:
                  $ref: '#/components/examples/invalid-genome_id-response'
        404:
          description: Genome ID not found
          content: {}
  /api/genome/karyotype:
    get:
      tags:
      - api
      summary: Returns information about karyotype
      description: Returns a karyotype for given genome
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Karyotype'
        400:
          description: Invalid Genome ID
          content: {}
        404:
          description: Genome not found
          content: {}
      security:
      - api_key: []
  /api/genome/region/validate:
    get:
      tags:
      - api
      summary: Returns information about karyotype
      description: Returns a karyotype for given genome
      parameters:
      - name: genome_id
        in: query
        description: ID of genome to return
        required: true
        schema:
          type: string
          default: homo_sapiens_GCA_000001405_27
      - name: region
        in: query
        description: region to validate
        required: true
        schema: 
          type: string
          default: 1:10000-1000000
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidatedRegion'
components:
  schemas:
    Genome:
      type: object
      properties:
        alternative_assemblies:
          type: array
          items:
            $ref: '#/components/schemas/Assembly'
        assembly_accession:
          type: string
          example: GCA_000001405.27
        assembly_name:
          type: string
          example: GRCh38.p12
        common_name:
          type: string
          example: Human
        division:
          type: array
          items:
            $ref: '#/components/schemas/Division/properties/division_name'
        example_objects:
          type: array
          items:
            $ref: '#/components/schemas/Object/properties/object_id'
        genome_id:
          type: string
          example: homo_sapiens_GCA_000001405_27
        image:
          type: string
          example: http://2020.ensembl.org/static/genome_images/homo_sapiens_GCA_000001405_27.svg
        is_available:
          type: boolean
          example: true
        is_strain:
          type: boolean
          example: false
        popular_order:
          type: integer
          format: int32
          example: 0
        production_name:
          type: string
          example: homo_sapiens
        reference_genome_id:
          type: string
          example: null
        scientific_name:
          type: string
          example: Homo sapiens
    Division:
      type: object
      properties:
        division_name:
          type: string
          example: EnsemblVertebrates
    Assembly:
      type: object
      properties:
        assembly_name:
          type: string
          example: GRCh37.p13
        genome_id:
          type: string
          example: homo_sapiens_GCA_000001405_14
    TrackList:
      type: object
      properties:
        additional_info:
          type: string
        child_tracks:
          type: array
          items:
            $ref: '#/components/schemas/ChildTrack'
        descirption:
          type: string
        ensembl_object_id:
          type: string
        label:
          type: string
        track_id:
          type: string
    TrackCategory:
      type: object
      properties:
        track_category_id:
          type: string
          example: genes-transcripts
        label:
          type: string
          example: Genes & transcripts
        track_list:
          type: array
          items:
            $ref: '#/components/schemas/Track'
        types:
          type: array
          items:
            type: string
            enum:
            - Genomic
            - Variation
            - Expression
    Track:
      type: object
      properties:
        track_id:
          type: string
          example: track:gene-pc-fwd
        label:
          type: string
          example: Protein coding genes
        color:
          type: string
          example: GREY
        additional_info:
          type: string
          example: Forward strand
    ChildTrack:
      type: object
      properties:
        additional_info:
          type: string
        color:
          type: string
        description:
          type: string
        ensembl_object_id:
          type: string
        label:
          type: string
        support_level:
          type: string
        track_id:
          type: string
    Object:
      type: object
      properties:
        bio_type:
          type: string
          example: "Protein Coding"
        description:
          type: string
          example: "BRCA2 DNA repair associated"
        genome_id:
          $ref: '#/components/schemas/Genome/properties/genome_id'
        label:
          type: string
          example: "BRCA2"
        location:
          $ref: '#/components/schemas/Location'
        object_id:
          type: string
          example: "gene:ENSG00000139618"
        object_type:
          type: string
          example: "gene"
        stable_id:
          type: string
          example: "ENSG00000139618"
        strand:
          type: string
          example: "forward"
        version_stable_id:
          type: string
          example: "ENSG00000139618.15"
    Location:
      type: object
      properties:
        chromosome:
          type: string
          example: "14"
        start:
          type: integer
          format: int64
          example: 32400266
        end:
          type: integer
          format: int64
          example: 32315086
    Karyotype:
      type: object
      properties:
        name:
          type: string
          example: "1"
        type:
          type: string
          example: "chromosome"
        length:
          type: integer
          example: 248956422
        is_chromosome:
          type: boolean
          example: true
        is_circular:
          type: boolean
          example: true
    ValidatedRegion: 
      type: object
      properties:
        genome_id:
          type: object
          properties:
            value: 
              type: string
            is_valid:
              type: boolean
            error_code:
              type: string
            error_message:
              type: string        
        start:
          type: object
          properties:
            value: 
              type: integer
            is_valid:
              type: boolean
            error_code:
              type: string
            error_message:
              type: string
        end:
          type: object
          properties:
            value: 
              type: integer
            is_valid:
              type: boolean
            error_code:
              type: string
            error_message:
              type: string
        region: 
          type: object
          properties:
            region_code: 
              type: string
            region_name:
              type: string
            is_valid:
              type: boolean
            error_code:
              type: string
            error_message:
              type: string
        region_id:
          $ref: '#/components/schemas/Object/properties/object_id' 
  examples:
    missing-genome_id-param-response:
      value:
        message: 
          {
          genome_id: "Missing genome_id param in the request." 
          }
    missing-genome_id-value-response:
      value:
        message: 
          {
          error: "No value for genome_id"
          }
    invalid-genome_id-response:
      value:
        message: 
          {
          error:  "Invalid genome_id : abc"
          }
    object-info-gene-response:
      value:
        bio_type: Protein coding
        description: BRCA2 DNA repair associated
        genome_id: homo_sapiens_GCA_000001405_27
        label: BRCA2
        location:
          chromosome: '13'
          end: 32400266
          start: 32315086
        object_id: 'gene:ENSG00000139618'
        object_type: gene
        stable_id: ENSG00000139618
        strand: forward
        versioned_stable_id: ENSG00000139618.15
    object-info-region-response:
      value:
        genome_id: homo_sapiens_GCA_000001405_27
        label: '17:63992802-64038237'
        location:
          chromosome: '17'
          end: '64038237'
          start: '63992802'
        object_id: 'region:17:63992802-64038237'
        object_type: region
    track-list-gene-response:
      value:
        additional_info: Protein coding
        child_tracks:
          - additional_info: Protein coding
            colour: BLUE
            description: 'BRCA2, DNA repair associated'
            ensembl_object_id: 'Transcript:ENST00000380152.7'
            label: ENST00000380152.7
            support_level: Canonical
            track_id: 'track:gene-feat-1'
        description: 'BRCA2, DNA repair associated'
        ensembl_object_id: 'gene:ENSG00000139618'
        label: BRCA2
        track_id: 'track:gene-feat'
    valid-region-response:
      value:
        end:
          error_code: null
          error_message: null
          is_valid: true
          value: 1000000
        genome_id:
          error_code: null
          error_message: null
          is_valid: true
          value: homo_sapiens_GCA_000001405_27
        region:
          error_code: null
          error_message: null
          is_valid: true
          region_code: chromosome
          region_name: '1'
        region_id: 'homo_sapiens_GCA_000001405_27:region:1:10000-1000000'
        start:
          error_code: null
          error_message: null
          is_valid: true
          value: 10000